export const PRODUCT_DATA = [
  {
    id: 1,
    logo: "https://via.placeholder.com/40",
    name: "Accardi Platinum",
    sku: "JVABP",
    description: "....",
    unit: "BA",
    price: "79.16",
    unitSoldLastMonth: "1200",
    unitSoldLastWeek: "412",
    category: "Vegetables",
  },
  {
    id: 2,
    logo: "https://via.placeholder.com/40",
    name: "Aleppo Pepper",
    sku: "UAP1",
    unit: "EA",
    description: "....",
    price: "13.85",
    unitSoldLastMonth: "100",
    unitSoldLastWeek: "24",
    category: "Vegetables",
  },
  {
    id: 3,
    logo: "https://via.placeholder.com/40",
    name: "Almonds Sliced",
    sku: "BASN5",
    unit: "CS",
    description: "....",
    price: "56.12",
    unitSoldLastMonth: "100",
    unitSoldLastWeek: "27",
    category: "Vegetables",
  },
  {
    id: 4,
    logo: "https://via.placeholder.com/40",
    name: "DeCecco BULK",
    sku: "OAVX3",
    unit: "BG",
    description: "....",
    price: "13.21",
    unitSoldLastMonth: "50",
    unitSoldLastWeek: "17",
    category: "Vegetables",
  },
  {
    id: 5,
    logo: "https://via.placeholder.com/40",
    name: "Penne Rigate",
    sku: "BASN5",
    unit: "BG",
    description: "....",
    price: "9.8",
    unitSoldLastMonth: "15",
    unitSoldLastWeek: "7",
    category: "Vegetables",
  },
  {
    id: 6,
    logo: "https://via.placeholder.com/40",
    name: "Egg Fett Nest",
    sku: "GA13",
    unit: "EA",
    description: "....",
    price: "35.67",
    unitSoldLastMonth: "32",
    unitSoldLastWeek: "12",
    category: "Vegetables",
  },
  {
    id: 7,
    logo: "https://via.placeholder.com/40",
    name: "Orecchiette",
    sku: "PBAL",
    unit: "EA",
    description: "....",
    price: "26.09",
    unitSoldLastMonth: "300",
    unitSoldLastWeek: "654",
    category: "Vegetables",
  },
  {
    id: 8,
    logo: "https://via.placeholder.com/40",
    name: "Mezzi Rigatoni",
    sku: "BASN6",
    unit: "CS",
    description: "....",
    price: "7.23",
    unitSoldLastMonth: "200",
    unitSoldLastWeek: "113",
    category: "Vegetables",
  },
  {
    id: 9,
    logo: "https://via.placeholder.com/40",
    name: "Linguine",
    sku: "UPAV1",
    unit: "BG",
    description: "....",
    price: "322.82",
    unitSoldLastMonth: "700",
    unitSoldLastWeek: "120",
    category: "Vegetables",
  },
  {
    id: 10,
    logo: "https://via.placeholder.com/40",
    name: "Conchigliette",
    sku: "OAVX3",
    unit: "CS",
    description: "....",
    price: "73.02",
    unitSoldLastMonth: "800",
    unitSoldLastWeek: "326",
    category: "Vegetables",
  },
  {
    id: 11,
    logo: "https://via.placeholder.com/40",
    name: "Shell Conchigliette",
    sku: "BATL1",
    unit: "BG",
    description: "....",
    price: "40",
    unitSoldLastMonth: "120",
    unitSoldLastWeek: "32",
    category: "Vegetables",
  },
  {
    id: 12,
    logo: "https://via.placeholder.com/40",
    name: "STRAWBERRY",
    sku: "UPAL5",
    unit: "BG",
    description: "....",
    price: "29",
    unitSoldLastMonth: "1700",
    unitSoldLastWeek: "478",
    category: "Fruits",
  },
  {
    id: 13,
    logo: "https://via.placeholder.com/40",
    name: "RASPBERRY",
    sku: "GAP10",
    unit: "BG",
    description: "....",
    price: "36.52",
    unitSoldLastMonth: "653",
    unitSoldLastWeek: "129",
    category: "Fruits",
  },
  {
    id: 14,
    logo: "https://via.placeholder.com/40",
    name: "Couscous",
    sku: "HGTL9",
    unit: "EA",
    description: "....",
    price: "28.38",
    unitSoldLastMonth: "562",
    unitSoldLastWeek: "200",
    category: "Vegetables",
  },
  {
    id: 15,
    logo: "https://via.placeholder.com/40",
    name: "Pancetta",
    sku: "BHGE2",
    unit: "BG",
    description: "....",
    price: "65.83",
    unitSoldLastMonth: "908",
    unitSoldLastWeek: "356",
    category: "Vegetables",
  },
  {
    id: 16,
    logo: "https://via.placeholder.com/40",
    name: "Fusilli",
    sku: "SFY75",
    unit: "CS",
    description: "....",
    price: "48.14",
    unitSoldLastMonth: "862",
    unitSoldLastWeek: "261",
    category: "Fruits",
  },
  {
    id: 17,
    logo: "https://via.placeholder.com/40",
    name: "Cavatelli",
    sku: "RFED4",
    unit: "BG",
    description: "....",
    price: "25.19",
    unitSoldLastMonth: "367",
    unitSoldLastWeek: "135",
    category: "Vegetables",
  },
  {
    id: 18,
    logo: "https://via.placeholder.com/40",
    name: "Cumin Whole",
    sku: "PLOK8",
    unit: "BG",
    description: "....",
    price: "93.48",
    unitSoldLastMonth: "784",
    unitSoldLastWeek: "235",
    category: "Vegetables",
  },
  {
    id: 19,
    logo: "https://via.placeholder.com/40",
    name: "Cream of Tartar",
    sku: "JHU61",
    unit: "EA",
    description: "....",
    price: "50.56",
    unitSoldLastMonth: "876",
    unitSoldLastWeek: "413",
    category: "Vegetables",
  },
  {
    id: 20,
    logo: "https://via.placeholder.com/40",
    name: "Large Pearls",
    sku: "GBFV7",
    unit: "CS",
    description: "....",
    price: "40.12",
    unitSoldLastMonth: "261",
    unitSoldLastWeek: "78",
    category: "Vegetables",
  },
  {
    id: 21,
    logo: "https://via.placeholder.com/40",
    name: "Corn Starch",
    sku: "DGBG8",
    unit: "BG",
    description: "....",
    price: "80.23",
    unitSoldLastMonth: "2610",
    unitSoldLastWeek: "948",
    category: "Vegetables",
  },
  {
    id: 22,
    logo: "https://via.placeholder.com/40",
    name: "Coriander Seed",
    sku: "BHG73",
    unit: "CS",
    description: "....",
    price: "64.80",
    unitSoldLastMonth: "744",
    unitSoldLastWeek: "289",
    category: "Vegetables",
  },
];
