export const PRODUCT_DATA = [
  {
    id: 1,
    logo: "https://via.placeholder.com/40",
    name: "Accardi Platinum",
    sku: "JVABP",
    description: "....",
    unit: "BA",
    price: "$79.16",
    unitSoldLastMonth: "1200",
    unitSoldLastWeek: "412",
    category: "Vegetables",
    largestBuyer: "Supermart",
    bestSalesRep: "Alice Johnson",
    bestMarket: "California",
    highestSalesDay: "Wednesday",
    highestSalesMonth: "March",
    inventoryAge: "20 days",
  },
  {
    id: 2,
    logo: "https://via.placeholder.com/40",
    name: "Aleppo Pepper",
    sku: "UAP1",
    unit: "EA",
    description: "....",
    price: "$13.85",
    unitSoldLastMonth: "100",
    unitSoldLastWeek: "24",
    category: "Vegetables",
    largestBuyer: "Grocery Outlet",
    bestSalesRep: "John Doe",
    bestMarket: "Texas",
    highestSalesDay: "Friday",
    highestSalesMonth: "July",
    inventoryAge: "35 days",
  },
  {
    id: 3,
    logo: "https://via.placeholder.com/40",
    name: "Almonds Sliced",
    sku: "BASN5",
    unit: "CS",
    description: "....",
    price: "$56.12",
    unitSoldLastMonth: "100",
    unitSoldLastWeek: "27",
    category: "Vegetables",
    largestBuyer: "Healthy Foods Co.",
    bestSalesRep: "Emily Clark",
    bestMarket: "New York",
    highestSalesDay: "Monday",
    highestSalesMonth: "September",
    inventoryAge: "15 days",
  },
  {
    id: 4,
    logo: "https://via.placeholder.com/40",
    name: "DeCecco BULK",
    sku: "OAVX3",
    unit: "BG",
    description: "....",
    price: "$13.21",
    unitSoldLastMonth: "50",
    unitSoldLastWeek: "17",
    category: "Vegetables",
    largestBuyer: "Market Basket",
    bestSalesRep: "Frank Wright",
    bestMarket: "Florida",
    highestSalesDay: "Thursday",
    highestSalesMonth: "December",
    inventoryAge: "28 days",
  },
  {
    id: 5,
    logo: "https://via.placeholder.com/40",
    name: "Penne Rigate",
    sku: "BASN5",
    unit: "BG",
    description: "....",
    price: "$9.8",
    unitSoldLastMonth: "15",
    unitSoldLastWeek: "7",
    category: "Vegetables",
    largestBuyer: "Big Value",
    bestSalesRep: "Rachel Adams",
    bestMarket: "Oregon",
    highestSalesDay: "Saturday",
    highestSalesMonth: "January",
    inventoryAge: "50 days",
  },
  {
    id: 6,
    logo: "https://via.placeholder.com/40",
    name: "Egg Fett Nest",
    sku: "GA13",
    unit: "EA",
    description: "....",
    price: "$35.67",
    unitSoldLastMonth: "32",
    unitSoldLastWeek: "12",
    category: "Vegetables",
    largestBuyer: "Whole Foods",
    bestSalesRep: "Chris Turner",
    bestMarket: "Washington",
    highestSalesDay: "Tuesday",
    highestSalesMonth: "May",
    inventoryAge: "40 days",
  },
  {
    id: 7,
    logo: "https://via.placeholder.com/40",
    name: "Orecchiette",
    sku: "PBAL",
    unit: "EA",
    description: "....",
    price: "$26.09",
    unitSoldLastMonth: "300",
    unitSoldLastWeek: "654",
    category: "Vegetables",
    largestBuyer: "Gourmet Foods",
    bestSalesRep: "Mia Zhang",
    bestMarket: "Arizona",
    highestSalesDay: "Sunday",
    highestSalesMonth: "February",
    inventoryAge: "22 days",
  },
  {
    id: 8,
    logo: "https://via.placeholder.com/40",
    name: "Mezzi Rigatoni",
    sku: "BASN6",
    unit: "CS",
    description: "....",
    price: "$7.23",
    unitSoldLastMonth: "200",
    unitSoldLastWeek: "113",
    category: "Vegetables",
    largestBuyer: "Save On",
    bestSalesRep: "Tom Lee",
    bestMarket: "Nevada",
    highestSalesDay: "Wednesday",
    highestSalesMonth: "October",
    inventoryAge: "18 days",
  },
  {
    id: 9,
    logo: "https://via.placeholder.com/40",
    name: "Linguine",
    sku: "UPAV1",
    unit: "BG",
    description: "....",
    price: "$322.82",
    unitSoldLastMonth: "700",
    unitSoldLastWeek: "120",
    category: "Vegetables",
    largestBuyer: "Lux Mart",
    bestSalesRep: "Sophia Martinez",
    bestMarket: "Utah",
    highestSalesDay: "Friday",
    highestSalesMonth: "June",
    inventoryAge: "12 days",
  },
  {
    id: 10,
    logo: "https://via.placeholder.com/40",
    name: "Conchigliette",
    sku: "OAVX3",
    unit: "CS",
    description: "....",
    price: "$73.02",
    unitSoldLastMonth: "800",
    unitSoldLastWeek: "326",
    category: "Vegetables",
    largestBuyer: "Food Circus",
    bestSalesRep: "Mike Brown",
    bestMarket: "Colorado",
    highestSalesDay: "Thursday",
    highestSalesMonth: "November",
    inventoryAge: "10 days",
  },
  {
    id: 11,
    logo: "https://via.placeholder.com/40",
    name: "Shell Conchigliette",
    sku: "BATL1",
    unit: "BG",
    description: "....",
    price: "$40",
    unitSoldLastMonth: "120",
    unitSoldLastWeek: "32",
    category: "Vegetables",
    largestBuyer: "Shop Quick",
    bestSalesRep: "Linda Harris",
    bestMarket: "Minnesota",
    highestSalesDay: "Monday",
    highestSalesMonth: "April",
    inventoryAge: "30 days",
  },
  {
    id: 12,
    logo: "https://via.placeholder.com/40",
    name: "STRAWBERRY",
    sku: "UPAL5",
    unit: "BG",
    description: "....",
    price: "$29",
    unitSoldLastMonth: "1700",
    unitSoldLastWeek: "478",
    category: "Fruits",
    largestBuyer: "Fresh Market",
    bestSalesRep: "Nancy Wilson",
    bestMarket: "Missouri",
    highestSalesDay: "Saturday",
    highestSalesMonth: "August",
    inventoryAge: "25 days",
  },
  {
    id: 13,
    logo: "https://via.placeholder.com/40",
    name: "RASPBERRY",
    sku: "GAP10",
    unit: "BG",
    description: "....",
    price: "$36.52",
    unitSoldLastMonth: "653",
    unitSoldLastWeek: "129",
    category: "Fruits",
    largestBuyer: "Nature's Basket",
    bestSalesRep: "George Carter",
    bestMarket: "Kentucky",
    highestSalesDay: "Tuesday",
    highestSalesMonth: "December",
    inventoryAge: "45 days",
  },
  {
    id: 14,
    logo: "https://via.placeholder.com/40",
    name: "Couscous",
    sku: "HGTL9",
    unit: "EA",
    description: "....",
    price: "$28.38",
    unitSoldLastMonth: "562",
    unitSoldLastWeek: "200",
    category: "Vegetables",
    largestBuyer: "City Market",
    bestSalesRep: "Samantha Lee",
    bestMarket: "Alaska",
    highestSalesDay: "Wednesday",
    highestSalesMonth: "March",
    inventoryAge: "20 days",
  },
  {
    id: 15,
    logo: "https://via.placeholder.com/40",
    name: "Pancetta",
    sku: "BHGE2",
    unit: "BG",
    description: "....",
    price: "$65.83",
    unitSoldLastMonth: "908",
    unitSoldLastWeek: "356",
    category: "Vegetables",
    largestBuyer: "Daily Grocer",
    bestSalesRep: "Kevin Smith",
    bestMarket: "Hawaii",
    highestSalesDay: "Friday",
    highestSalesMonth: "July",
    inventoryAge: "35 days",
  },
  {
    id: 16,
    logo: "https://via.placeholder.com/40",
    name: "Fusilli",
    sku: "SFY75",
    unit: "CS",
    description: "....",
    price: "$48.14",
    unitSoldLastMonth: "862",
    unitSoldLastWeek: "261",
    category: "Fruits",
    largestBuyer: "Bountiful Harvest",
    bestSalesRep: "Olivia Taylor",
    bestMarket: "Idaho",
    highestSalesDay: "Monday",
    highestSalesMonth: "September",
    inventoryAge: "15 days",
  },
  {
    id: 17,
    logo: "https://via.placeholder.com/40",
    name: "Cavatelli",
    sku: "RFED4",
    unit: "BG",
    description: "....",
    price: "$25.19",
    unitSoldLastMonth: "367",
    unitSoldLastWeek: "135",
    category: "Vegetables",
    largestBuyer: "Planet Organic",
    bestSalesRep: "Frank Wright",
    bestMarket: "Iowa",
    highestSalesDay: "Thursday",
    highestSalesMonth: "December",
    inventoryAge: "28 days",
  },
  {
    id: 18,
    logo: "https://via.placeholder.com/40",
    name: "Cumin Whole",
    sku: "PLOK8",
    unit: "BG",
    description: "....",
    price: "$93.48",
    unitSoldLastMonth: "784",
    unitSoldLastWeek: "235",
    category: "Vegetables",
    largestBuyer: "Earth Fare",
    bestSalesRep: "Rachel Adams",
    bestMarket: "Vermont",
    highestSalesDay: "Saturday",
    highestSalesMonth: "January",
    inventoryAge: "50 days",
  },
  {
    id: 19,
    logo: "https://via.placeholder.com/40",
    name: "Cream of Tartar",
    sku: "JHU61",
    unit: "EA",
    description: "....",
    price: "$50.56",
    unitSoldLastMonth: "876",
    unitSoldLastWeek: "413",
    category: "Vegetables",
    largestBuyer: "Green Grocer",
    bestSalesRep: "Chris Turner",
    bestMarket: "North Dakota",
    highestSalesDay: "Tuesday",
    highestSalesMonth: "May",
    inventoryAge: "40 days",
  },
  {
    id: 20,
    logo: "https://via.placeholder.com/40",
    name: "Large Pearls",
    sku: "GBFV7",
    unit: "CS",
    description: "....",
    price: "$40.12",
    unitSoldLastMonth: "261",
    unitSoldLastWeek: "78",
    category: "Vegetables",
    largestBuyer: "Fine Foods",
    bestSalesRep: "Mia Zhang",
    bestMarket: "Montana",
    highestSalesDay: "Sunday",
    highestSalesMonth: "February",
    inventoryAge: "22 days",
  },
  {
    id: 21,
    logo: "https://via.placeholder.com/40",
    name: "Corn Starch",
    sku: "DGBG8",
    unit: "BG",
    description: "....",
    price: "$80.23",
    unitSoldLastMonth: "2610",
    unitSoldLastWeek: "948",
    category: "Vegetables",
    largestBuyer: "Kwik-E-Mart",
    bestSalesRep: "Tom Lee",
    bestMarket: "Oklahoma",
    highestSalesDay: "Wednesday",
    highestSalesMonth: "October",
    inventoryAge: "18 days",
  },
  {
    id: 22,
    logo: "https://via.placeholder.com/40",
    name: "Coriander Seed",
    sku: "BHG73",
    unit: "CS",
    description: "....",
    price: "$64.80",
    unitSoldLastMonth: "744",
    unitSoldLastWeek: "289",
    category: "Vegetables",
    largestBuyer: "Organic Corner",
    bestSalesRep: "Sophia Martinez",
    bestMarket: "Utah",
    highestSalesDay: "Friday",
    highestSalesMonth: "June",
    inventoryAge: "12 days",
  },
];
