export const SALES_REP = [
  {
    id: 1,
    firstName: "Usman",
    lastName: "Asif",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Bistro",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:20",
    averageWeeklySale: "30%",
    weeklyTrend: "$40.23",
    monthlyTrend: "-30",
  },
  {
    id: 2,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Indian",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "3:5",
    averageWeeklySale: "12%",
    weeklyTrend: "$12.18",
    monthlyTrend: "30",
  },
  {
    id: 3,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:7",
    averageWeeklySale: "2%",
    weeklyTrend: "$24.12",
    monthlyTrend: "-4",
  },
  {
    id: 4,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "4:2",
    averageWeeklySale: "54%",
    weeklyTrend: "$30.93",
    monthlyTrend: "4",
  },
  {
    id: 5,
    firstName: "Usman",
    lastName: "Asif",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Indian",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:20",
    averageWeeklySale: "30%",
    weeklyTrend: "$40.23",
    monthlyTrend: "-30",
  },
  {
    id: 6,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Bistro",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "3:5",
    averageWeeklySale: "12%",
    weeklyTrend: "$12.18",
    monthlyTrend: "30",
  },
  {
    id: 7,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Bistro",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:7",
    averageWeeklySale: "2%",
    weeklyTrend: "$24.12",
    monthlyTrend: "-4",
  },
  {
    id: 8,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "4:2",
    averageWeeklySale: "54%",
    weeklyTrend: "$30.93",
    monthlyTrend: "4",
  },
  {
    id: 9,
    firstName: "Usman",
    lastName: "Asif",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Indian",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:20",
    averageWeeklySale: "30%",
    weeklyTrend: "$40.23",
    monthlyTrend: "-30",
  },
  {
    id: 10,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "3:5",
    averageWeeklySale: "12%",
    weeklyTrend: "$12.18",
    monthlyTrend: "30",
  },
  {
    id: 11,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:7",
    averageWeeklySale: "2%",
    weeklyTrend: "$24.12",
    monthlyTrend: "-4",
  },
  {
    id: 12,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Indian",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "4:2",
    averageWeeklySale: "54%",
    weeklyTrend: "$30.93",
    monthlyTrend: "4",
  },
  {
    id: 13,
    firstName: "Usman",
    lastName: "Asif",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Chinese",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:20",
    averageWeeklySale: "30%",
    weeklyTrend: "$40.23",
    monthlyTrend: "-30",
  },
  {
    id: 14,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Italian",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "3:5",
    averageWeeklySale: "12%",
    weeklyTrend: "$12.18",
    monthlyTrend: "30",
  },
  {
    id: 7,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Maxico",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "10:7",
    averageWeeklySale: "2%",
    weeklyTrend: "$24.12",
    monthlyTrend: "-4",
  },
  {
    id: 15,
    firstName: "Asif",
    lastName: "Usman",
    phoneNo: "+187439824",
    territory: "All",
    salesRep: "TO Market",
    restaurentType: "Buffet",
    highestSellingAccount: "WhatChefWants",
    salesRatio: "4:2",
    averageWeeklySale: "54%",
    weeklyTrend: "$30.93",
    monthlyTrend: "4",
  },
];
